# Generated by Django 3.1.2 on 2021-01-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20210110_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='keijiban',
            name='goodtext',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
