# Generated by Django 3.1.2 on 2021-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_keijiban_goodtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keijiban',
            name='goodtext',
            field=models.CharField(blank=True, default='a', max_length=10000, null=True),
        ),
    ]
