# Generated by Django 3.1.2 on 2021-01-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_auto_20210116_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keijiban',
            name='goodtext',
            field=models.CharField(blank=True, default='/', max_length=10000, null=True),
        ),
    ]
