# Generated by Django 3.1.2 on 2021-01-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0008_auto_20210116_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='keijiban',
            name='goodman_list_field',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
