# Generated by Django 3.1.2 on 2021-01-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0009_keijiban_goodman_list_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keijiban',
            name='goodman_list_field',
            field=models.CharField(blank=True, default='/', max_length=10000, null=True),
        ),
    ]
