# Generated by Django 3.1.2 on 2021-01-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0011_auto_20210117_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keijiban',
            name='goodtext',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
