# Generated by Django 3.1.2 on 2021-02-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0014_auto_20210119_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='keijiban',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
