# Generated by Django 3.1.2 on 2021-02-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0015_keijiban_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keijiban',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='keijiban',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
