# Generated by Django 3.1.2 on 2021-02-01 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0016_auto_20210201_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keijiban',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
