# Generated by Django 3.1.2 on 2021-02-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0018_auto_20210221_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keijiban',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
